name: KonseptGate
main: com.webkonsept.bukkit.konseptgate.KG
version: 0.3
branch: stable
website: http://minecraft.webkonsept.com/plugins/details/KonseptGate.html
location: http://minecraft.webkonsept.com/plugins/download/KonseptGate.jar
thread: http://forums.bukkit.org/threads/KonseptGate.25907/
database: false
description: Simplified/stripped-down teleport/gating plugin
commands:
    kg:
        aliases: 
        description: Takes the selected action against the indicated gate(s)
        usage: /kg [create|move|delete|link|jump|ignore|reload|list] <gate(s)>
generators: [bukget]
categories: [TP]
maintainer: DemmyDemon
authors: [DemmyDemon]
conflicts: []
required: []
optional: []
engines:
    craftbukkit:
        min: 1597
        max: 1597
permissions:
    konseptgate.*:
        description: Gives full access
        children:
            konseptgate.command.*: true
            konseptgate.teleport: true
            konseptgate.info: true
    konseptgate.command.*:
        description: Gives access to all commands
        children:
            konseptgate.command.link: true
            konseptgate.command.create: true
            konseptgate.command.move: true
            konseptgate.command.delete: true
            konseptgate.command.list: true
            konseptgate.command.reload: true
            konseptgate.command.jump: true
            konseptgate.command.ignore: true
    konseptgate.command.link:
        description: Gives access to the /kg link command
        default: op
    konseptgate.command.create:
        description: Gives access to the /kg create command
        default: op
    konseptgate.command.move:
        description: Gives access to the /kg move command
        default: op
    konseptgate.command.delete:
        description: Gives access to the /kg delete command
        default: op
    konseptgate.command.list:
        description: Gives access to the /kg list command
        default: op
    konseptgate.command.reload:
        description: Gives access to the /kg reload command
        default: op
    konseptgate.command.jump:
        description: Gives access to the /kg jump command
        default: op
    konseptgate.command.ignore:
        description: Gives access to the /kg ignore command
        default: op
    konseptgate.teleport:
        description: The business end of this plugin
        default: true
    konseptgate.info:
        description: Right-click a telepad for info
        defauilt: op
